DATALOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 8

TRAINING:
  LOGGING_PERIOD: 200
  EPOCHS: 1000
  CHECKPOINT: './checkpoints/'


SOLVER:
  lr: 0.0001
  weight_decay: 0.0001
  beta1: 0.9
  beta2: 0.95
  warmup_epochs: 40
  min_lr: 0.0000001

MODEL:
  img_size: [128,128,128]
  patch_size: 16
  in_chans: 1
  embed_dim: 768
  depth: 12
  n_heads: 12
  qkv_bias: True
  drop_path_rate: 0.
  decoder_embed_dim: 576
  decoder_depth: 8
  decoder_num_heads: 16
  norm_pix_loss: False
  mlp_ratio: 4.0

